import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { toast } from 'sonner';
import PortalShell from '../../components/phase2/PortalShell';
import { personalisationService, type SavedSearchInput } from '../../services/personalisationService';
import type { FavouriteItem, RecentlyViewedItem, SavedSearch } from '../../types';
const blank: SavedSearchInput = { name: '', filters: {}, alerts: { enabled: true, cadence: 'daily', channels: { inApp: true, email: false } } };
export default function Personalisation() {
  const [tab, setTab] = useState<'favourites' | 'searches' | 'recent'>('favourites'); const [favourites, setFavourites] = useState<FavouriteItem[]>([]);
  const [searches, setSearches] = useState<SavedSearch[]>([]); const [recent, setRecent] = useState<RecentlyViewedItem[]>([]); const [form, setForm] = useState(blank); const [error, setError] = useState('');
  const load = async () => { setError(''); try { const [a,b,c] = await Promise.all([personalisationService.favourites(), personalisationService.searches(), personalisationService.recent()]); setFavourites(a.favourites); setSearches(b.savedSearches); setRecent(c.recentlyViewed); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load personalisation.'); } };
  // Initial server hydration is intentionally user scoped.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, []);
  const propertyRow = (property: FavouriteItem['property'], action: React.ReactNode) => <article key={property.publicReference} className='bg-white border rounded-xl p-4 flex justify-between gap-4'><div><Link className='font-bold text-primary' to={`/properties/${property.publicReference}`}>{property.title}</Link><p className='text-sm text-slate-500'>{property.location}</p></div>{action}</article>;
  return <PortalShell><main className='max-w-5xl mx-auto p-4 md:p-8'><h1 className='text-3xl font-extrabold mb-2'>Saved marketplace activity</h1><p className='text-slate-500 mb-6'>Manage favourites, searches and recent properties from server-backed history.</p>
    {error && <p role='alert' className='bg-red-50 text-red-800 p-3 rounded mb-4'>{error}</p>}
    <nav aria-label='Personalisation sections' className='flex flex-wrap gap-2 mb-6'>{(['favourites','searches','recent'] as const).map((item) => <button key={item} aria-current={tab === item ? 'page' : undefined} className={`px-4 py-2 rounded-full capitalize ${tab === item ? 'bg-primary text-white' : 'bg-white border'}`} onClick={() => setTab(item)}>{item}</button>)}</nav>
    {tab === 'favourites' && <section className='space-y-3'>{favourites.length ? favourites.map(({ property }) => propertyRow(property, <button className='text-red-700 underline' onClick={() => { const previous = favourites; setFavourites((items) => items.filter((x) => x.property.publicReference !== property.publicReference)); void personalisationService.setFavourite(property.publicReference, false).catch((e: Error) => { setFavourites(previous); toast.error(e.message); }); }}>Remove</button>)) : <p>No saved properties.</p>}</section>}
    {tab === 'recent' && <section><div className='flex justify-end mb-3'><button className='underline' onClick={() => void personalisationService.clearRecent().then(() => setRecent([]))}>Clear history</button></div><div className='space-y-3'>{recent.length ? recent.map(({ property }) => propertyRow(property, <button className='text-red-700 underline' onClick={() => void personalisationService.removeRecent(property.publicReference).then(() => setRecent((items) => items.filter((x) => x.property.publicReference !== property.publicReference)))}>Remove</button>)) : <p>No recently viewed properties.</p>}</div></section>}
    {tab === 'searches' && <section><form className='bg-white border rounded-xl p-5 grid grid-cols-1 md:grid-cols-3 gap-3 mb-6' onSubmit={(event) => { event.preventDefault(); if (form.filters.minPrice && form.filters.maxPrice && form.filters.minPrice > form.filters.maxPrice) { setError('Minimum price cannot exceed maximum price.'); return; } void personalisationService.createSearch(form).then((saved) => { setSearches((items) => [saved, ...items]); setForm(blank); toast.success('Search saved.'); }, (e: Error) => setError(e.message)); }}>
      <label>Name<input required className='block w-full border rounded p-2' value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label>
      <label>Location<input className='block w-full border rounded p-2' value={form.filters.location ?? ''} onChange={(e) => setForm({ ...form, filters: { ...form.filters, location: e.target.value || undefined } })} /></label>
      <label>Property type<select className='block w-full border rounded p-2' value={form.filters.propertyType ?? ''} onChange={(e) => setForm({ ...form, filters: { ...form.filters, propertyType: e.target.value || undefined } })}><option value=''>Any</option>{['house','apartment','commercial','villa','penthouse','estate'].map((x) => <option key={x}>{x}</option>)}</select></label>
      <label>Minimum price<input min='0' type='number' className='block w-full border rounded p-2' value={form.filters.minPrice ?? ''} onChange={(e) => setForm({ ...form, filters: { ...form.filters, minPrice: e.target.value ? Number(e.target.value) : undefined } })} /></label>
      <label>Maximum price<input min='0' type='number' className='block w-full border rounded p-2' value={form.filters.maxPrice ?? ''} onChange={(e) => setForm({ ...form, filters: { ...form.filters, maxPrice: e.target.value ? Number(e.target.value) : undefined } })} /></label>
      <label>Cadence<select className='block w-full border rounded p-2' value={form.alerts.cadence} onChange={(e) => setForm({ ...form, alerts: { ...form.alerts, cadence: e.target.value as SavedSearchInput['alerts']['cadence'] } })}>{['instant','daily','weekly'].map((x) => <option key={x}>{x}</option>)}</select></label>
      <label className='flex gap-2 items-center'><input type='checkbox' checked={form.alerts.enabled} onChange={(e) => setForm({ ...form, alerts: { ...form.alerts, enabled: e.target.checked } })} />Alerts enabled</label>
      <label className='flex gap-2 items-center'><input type='checkbox' checked={form.alerts.channels.email} onChange={(e) => setForm({ ...form, alerts: { ...form.alerts, channels: { ...form.alerts.channels, email: e.target.checked } } })} />Email alerts</label>
      <button className='bg-primary text-white rounded p-2'>Save search</button>
    </form><div className='space-y-3'>{searches.map((search) => <article key={search._id} className='bg-white border rounded-xl p-4'><div className='flex justify-between gap-3'><div><h2 className='font-bold'>{search.name}</h2><p className='text-sm text-slate-500'>{search.filters.location || 'Any location'} · {search.alerts.enabled ? `${search.alerts.cadence} alerts` : 'Alerts off'}</p></div><div className='flex gap-3'><button className='underline' onClick={() => { const name = window.prompt('Rename saved search', search.name)?.trim(); if (name) void personalisationService.updateSearch(search.publicReference, { name }).then((updated) => setSearches((items) => items.map((x) => x._id === updated._id ? updated : x))); }}>Rename</button><button className='text-red-700 underline' onClick={() => { if (window.confirm('Delete this saved search?')) void personalisationService.deleteSearch(search.publicReference).then(() => setSearches((items) => items.filter((x) => x._id !== search._id))); }}>Delete</button></div></div></article>)}</div></section>}
  </main></PortalShell>;
}
