import { useCallback, useEffect, useRef, useState } from 'react';
import Swal from 'sweetalert2';
import { toast } from 'sonner';
import { useAuth } from '../../contexts/AuthContext';
import { escrowErrorDetails, escrowService } from '../../services/escrowService';
import type { Escrow, RefundChatResponse } from '../../types/escrow';
import { populated } from '../../types/escrow';
import ErrorState from '../ui/ErrorState';
import LoadingState from '../ui/LoadingState';
import { formatDateTime } from './escrowConfig';

const RefundChat = ({ escrow, onChanged }: { escrow: Escrow; onChanged: () => void | Promise<unknown> }) => {
  const { user } = useAuth();
  const [chat, setChat] = useState<RefundChatResponse | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState(''); const [sending, setSending] = useState(false); const endRef = useRef<HTMLDivElement>(null);
  const load = useCallback(async (quiet = false) => { if (!quiet) setLoading(true); try { const result = await escrowService.getRefundChat(escrow._id); setChat({ ...result, messages: [...(result.messages ?? [])].sort((a, b) => Date.parse(a.createdAt) - Date.parse(b.createdAt)) }); setError(null); } catch (raw) { const err = escrowErrorDetails(raw); setError(err.status === 403 ? 'You do not have permission to view this refund conversation.' : err.status === 404 ? 'The refund conversation was not found.' : err.message); } finally { if (!quiet) setLoading(false); } }, [escrow._id]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { endRef.current?.scrollIntoView({ block: 'nearest' }); }, [chat?.messages.length]);
  useEffect(() => { if (chat?.conversation?.status === 'closed') return; const tick = () => { if (document.visibilityState === 'visible') void load(true); }; const timer = window.setInterval(tick, 15_000); document.addEventListener('visibilitychange', tick); return () => { window.clearInterval(timer); document.removeEventListener('visibilitychange', tick); }; }, [chat?.conversation?.status, load]);
  if (!user || !['buyer', 'admin'].includes(user.role)) return null;
  const request = async () => { const result = await Swal.fire<string>({ title: 'Request refund account details', input: 'textarea', inputLabel: 'Instruction to buyer', inputValue: 'Please provide the bank account details required to process your refund.', showCancelButton: true, confirmButtonText: 'Send request', confirmButtonColor: '#173d32', inputValidator: (value) => !value.trim() ? 'Enter an instruction.' : undefined }); if (!result.isConfirmed || sending) return; setSending(true); try { await escrowService.requestRefundDetails(escrow._id, result.value); toast.success('Request sent.'); await Promise.all([load(), onChanged()]); } catch (raw) { toast.error(escrowErrorDetails(raw).message); await load(); } finally { setSending(false); } };
  const send = async () => { const value = message.trim(); if (!value || sending || chat?.conversation?.status !== 'open') return; setSending(true); try { await escrowService.sendRefundMessage(escrow._id, value); setMessage(''); toast.success('Message sent.'); await Promise.all([load(), onChanged()]); } catch (raw) { const err = escrowErrorDetails(raw); if (err.status === 409) { toast.error('This refund conversation is closed.'); await load(); } else toast.error(err.message); } finally { setSending(false); } };
  return <section id="refund-chat" className="rounded-xl bg-white p-5 sm:p-7" aria-labelledby="refund-chat-title"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 id="refund-chat-title" className="text-xl font-bold">Refund conversation</h2><p className="mt-1 text-sm text-secondary">Use this conversation only to coordinate refund account details.</p></div>{user.role === 'admin' && escrow.status === 'refund_pending' && !chat?.conversation ? <button type="button" disabled={sending} onClick={() => void request()} className="rounded-lg bg-primary px-4 py-2 text-sm font-bold text-on-primary disabled:opacity-50">Request account details</button> : null}</div>
    {loading ? <LoadingState label="Loading refund conversation..." /> : error ? <ErrorState message={error} onRetry={() => void load()} /> : !chat?.conversation ? <div className="mt-5 rounded-lg bg-surface-container-low p-5 text-sm text-secondary">{user.role === 'admin' ? 'No conversation exists yet. Request the buyer’s account details to open it.' : 'An administrator has not opened the refund conversation yet. You can return here when details are requested.'}</div> : <><div className="mt-5 max-h-96 space-y-3 overflow-y-auto rounded-lg bg-surface-container-low p-4" role="log" aria-live="polite">{chat.messages.length ? chat.messages.map((item) => { const sender = populated(item.sender); const mine = typeof item.sender === 'string' ? item.sender === user._id : item.sender?._id === user._id; return <article key={item._id} className={`max-w-[85%] rounded-xl p-3 text-sm ${mine ? 'ml-auto bg-primary text-on-primary' : 'bg-white'}`}><strong className="block text-xs">{mine ? 'You' : sender?.role === 'admin' ? 'RealtiQ admin' : sender?.name ?? 'Buyer'}</strong><p className="mt-1 whitespace-pre-wrap break-words">{item.message}</p><time className="mt-2 block text-[10px] opacity-70">{formatDateTime(item.createdAt)}</time></article>; }) : <p className="text-sm text-secondary">No messages yet.</p>}<div ref={endRef} tabIndex={-1} /></div>{chat.conversation.status === 'closed' ? <p role="status" className="mt-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">This conversation is closed because refund processing is complete.</p> : <form className="mt-4 flex gap-2" onSubmit={(event) => { event.preventDefault(); void send(); }}><label className="sr-only" htmlFor="refund-message">Refund message</label><textarea id="refund-message" value={message} onChange={(event) => setMessage(event.target.value)} rows={2} maxLength={2000} placeholder="Write a message" className="min-w-0 flex-1 rounded-lg border border-outline-variant/30 p-3 text-sm" /><button type="submit" disabled={sending || !message.trim()} className="self-end rounded-lg bg-primary px-4 py-3 font-bold text-on-primary disabled:opacity-50">{sending ? 'Sending...' : 'Send'}</button></form>}</>}
  </section>;
};
export default RefundChat;
