import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import Swal from 'sweetalert2';
import { toast } from 'sonner';
import EscrowRoleLayout from '../../../components/escrow/EscrowRoleLayout';
import EscrowStatusBadge from '../../../components/escrow/EscrowStatusBadge';
import RefundAdminPanel from '../../../components/escrow/RefundAdminPanel';
import RefundChat from '../../../components/escrow/RefundChat';
import { ESCROW_STATUS, RULE_LABELS, canSatisfyRule, escrowActions, formatDateTime, formatEscrowMoney, requiredProgress } from '../../../components/escrow/escrowConfig';
import ErrorState from '../../../components/ui/ErrorState';
import LoadingState from '../../../components/ui/LoadingState';
import MediaPreview from '../../../components/property/MediaPreview';
import { useAuth } from '../../../contexts/AuthContext';
import { useAsync } from '../../../hooks/useAsync';
import { escrowErrorDetails, escrowService } from '../../../services/escrowService';
import type { Escrow } from '../../../types/escrow';
import { escrowBuyer, escrowPayment, escrowProperty, escrowSeller, isRuleSatisfied, populated } from '../../../types/escrow';

type Action = 'request' | 'approve' | 'cancel' | 'dispute';
const refundStatuses = ['refund_pending', 'refund_processing', 'refunded', 'refund_failed'];
const notePrompt = (title: string, required: boolean, confirmButtonText: string) => Swal.fire<string>({ title, input: 'textarea', inputLabel: required ? 'Reason (required)' : 'Audit note (optional)', inputPlaceholder: 'Add context for the audit timeline', showCancelButton: true, confirmButtonText, confirmButtonColor: '#173d32', inputValidator: (value) => required && !value.trim() ? 'A reason is required.' : undefined });
const actorName = (value: unknown) => { const actor = populated(value as { _id: string; name?: string } | string | null); return actor?.name ?? (typeof value === 'string' ? 'Participant' : 'System'); };
const metadataText = (metadata?: Record<string, unknown>) => metadata && Object.keys(metadata).length ? JSON.stringify(metadata) : null;

const EscrowDetails = () => {
  const { id = '' } = useParams(); const { user } = useAuth();
  const { data: escrow, loading, error, execute } = useAsync(() => escrowService.get(id), true);
  const [pending, setPending] = useState<string | null>(null); const [conflict, setConflict] = useState<string | null>(null); const [ruleEligibility, setRuleEligibility] = useState<Record<string, string>>({});
  const property = escrow ? escrowProperty(escrow) : null; const buyer = escrow ? escrowBuyer(escrow) : null; const seller = escrow ? escrowSeller(escrow) : null; const payment = escrow ? escrowPayment(escrow) : null;
  const progress = useMemo(() => escrow ? requiredProgress(escrow) : null, [escrow]);
  useEffect(() => { if (escrow?.status !== 'refund_processing') return; const refresh = () => { if (document.visibilityState === 'visible') void execute(); }; const timer = window.setInterval(refresh, 15_000); document.addEventListener('visibilitychange', refresh); return () => { window.clearInterval(timer); document.removeEventListener('visibilitychange', refresh); }; }, [escrow?.status, execute]);
  const mutate = async (key: string, operation: () => Promise<Escrow>) => { if (pending) return; setPending(key); setConflict(null); try { await operation(); toast.success('Escrow updated successfully.'); await execute(); } catch (raw) { const err = escrowErrorDetails(raw); if (err.status === 409) { const missing = Array.isArray(err.missingRules) ? err.missingRules.map((item) => typeof item === 'string' ? item : (item as { description?: string }).description ?? 'Required condition').join(', ') : ''; if (err.eligibleAt && key.startsWith('rule-')) setRuleEligibility((current) => ({ ...current, [key.slice(5)]: err.eligibleAt! })); setConflict(`${err.message}${missing ? ` Missing: ${missing}.` : ''}`); await execute(); } else if (err.status === 403) toast.error('You do not have permission to perform this escrow action.'); else if (err.status === 404) toast.error('This escrow is no longer available.'); else toast.error(err.message); } finally { setPending(null); } };
  const action = async (type: Action) => { if (!escrow) return; const settings: readonly [string, boolean, string] = type === 'dispute' ? ['Raise a dispute', true, 'Submit dispute'] : type === 'cancel' ? ['Cancel this escrow?', true, 'Cancel escrow'] : type === 'approve' ? ['Approve final release?', false, 'Approve release'] : ['Request release?', false, 'Request release']; const result = await notePrompt(settings[0], settings[1], settings[2]); if (!result.isConfirmed) return; const note = result.value?.trim() ?? ''; if (type === 'dispute') await mutate(type, () => escrowService.dispute(escrow._id, note)); if (type === 'cancel') await mutate(type, () => escrowService.cancel(escrow._id, note)); if (type === 'request') await mutate(type, () => escrowService.requestRelease(escrow._id, note)); if (type === 'approve') await mutate(type, () => escrowService.approveRelease(escrow._id, note)); };
  const satisfy = async (ruleId: string) => { if (!escrow) return; const result = await notePrompt('Mark condition as satisfied?', false, 'Confirm condition'); if (result.isConfirmed) await mutate(`rule-${ruleId}`, () => escrowService.satisfyRule(escrow._id, ruleId, result.value)); };
  const initialize = async () => { if (!escrow || pending) return; const result = await Swal.fire({ title: 'Continue to secured payment?', text: 'Paystack will process the charge. A successful payment locks funds in escrow; it does not complete the property purchase.', icon: 'question', showCancelButton: true, confirmButtonText: 'Continue to Paystack', confirmButtonColor: '#173d32' }); if (!result.isConfirmed) return; setPending('payment'); try { escrowService.redirectToPayment(await escrowService.initializePayment(escrow._id)); } catch (raw) { toast.error(escrowErrorDetails(raw).message); setPending(null); } };

  if (loading) return <EscrowRoleLayout title="Escrow Details"><LoadingState label="Loading escrow..." /></EscrowRoleLayout>;
  if (error || !escrow || !progress) return <EscrowRoleLayout title="Escrow Details"><ErrorState message={error ?? 'Escrow not found or access was denied.'} onRetry={() => void execute()} /></EscrowRoleLayout>;
  const refundEscrow = refundStatuses.includes(escrow.status); const actions = escrowActions(user?.role ?? 'buyer', escrow);
  const soldCancellation = escrow.status === 'cancelled' && (escrow.logs ?? []).some((log) => /sold|competing/i.test(`${log.action} ${log.note ?? ''}`));
  return <EscrowRoleLayout title="Escrow Details" subtitle={ESCROW_STATUS[escrow.status].description}>
    {conflict ? <div role="alert" className="mb-6 rounded-xl bg-amber-100 p-4 text-sm font-medium text-amber-900">{conflict}</div> : null}
    {soldCancellation ? <div role="status" className="mb-6 rounded-xl bg-slate-100 p-4 text-sm text-slate-800">This unpaid escrow was cancelled because the property was sold through another completed transaction. The property remains sold.</div> : null}
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-6">
      <section className="rounded-xl bg-white p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row"><div className="h-40 w-full overflow-hidden rounded-xl bg-surface-container-low sm:w-56"><MediaPreview media={property?.media?.[0]} alt={property?.title ?? 'Property'} className="h-full w-full object-cover" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">{property?.title ?? 'Property escrow'}</h2><p className="text-sm text-secondary">{property?.location ?? 'Location unavailable'}</p></div><EscrowStatusBadge status={escrow.status} /></div><p className="mt-5 text-3xl font-black text-primary">{formatEscrowMoney(escrow.amount, escrow.currency ?? property?.currency)}</p>{property ? <Link to={`/properties/${property._id}`} className="mt-3 inline-block text-sm font-bold text-primary hover:underline">View property details</Link> : null}</div></div><dl className="mt-6 grid gap-4 border-t border-outline-variant/20 pt-6 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs font-bold uppercase text-secondary">Buyer</dt><dd>{buyer?.name ?? '—'}</dd></div><div><dt className="text-xs font-bold uppercase text-secondary">Seller</dt><dd>{seller?.name ?? '—'}</dd></div><div><dt className="text-xs font-bold uppercase text-secondary">Created</dt><dd>{formatDateTime(escrow.createdAt)}</dd></div><div><dt className="text-xs font-bold uppercase text-secondary">Payment</dt><dd>{payment?.status ?? (escrow.status === 'pending_payment' ? 'Awaiting payment' : 'Confirmed')}</dd></div></dl></section>
      {refundEscrow ? <section className="rounded-xl bg-white p-5 sm:p-7"><h2 className="text-xl font-bold">Refund summary</h2><p className="mt-2 text-sm text-secondary">This property remains sold. The refund affects only this competing escrow’s secured payment.</p><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="font-bold text-secondary">Refund status</dt><dd>{ESCROW_STATUS[escrow.status].label}</dd></div><div><dt className="font-bold text-secondary">Requested</dt><dd>{formatDateTime(escrow.refundRequestedAt ?? undefined)}</dd></div><div><dt className="font-bold text-secondary">Processing started</dt><dd>{formatDateTime(escrow.refundProcessingAt ?? undefined)}</dd></div><div><dt className="font-bold text-secondary">Completed</dt><dd>{formatDateTime(escrow.refundedAt ?? undefined)}</dd></div>{escrow.refundReference ? <div><dt className="font-bold text-secondary">Refund reference</dt><dd className="break-all">{escrow.refundReference}</dd></div> : null}</dl>{escrow.status === 'refund_failed' ? <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">Refund processing was unsuccessful. {user?.role === 'admin' && escrow.refundFailureReason ? escrow.refundFailureReason : 'An administrator will review and retry it.'}</p> : null}</section> : <section className="rounded-xl bg-white p-5 sm:p-7"><div className="flex justify-between"><h2 className="text-xl font-bold">Required conditions</h2><strong>{progress.complete}/{progress.total}</strong></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-surface-container"><div className="h-full bg-primary" style={{ width: `${progress.percent}%` }} /></div><div className="mt-6 space-y-3">{(escrow.rules ?? []).map((rule) => { const satisfied = isRuleSatisfied(rule); const eligibleAt = ruleEligibility[rule._id]; return <article key={rule._id} className="rounded-xl border border-outline-variant/20 p-4"><div className="flex items-start gap-3"><span className="material-symbols-outlined">{satisfied ? 'check_circle' : 'radio_button_unchecked'}</span><div className="flex-1"><h3 className="font-bold">{RULE_LABELS[rule.type]}</h3><p className="text-sm text-secondary">{rule.description}</p>{eligibleAt ? <p className="text-xs text-amber-700">Eligible {formatDateTime(eligibleAt)}</p> : null}</div>{user && canSatisfyRule(user.role, escrow, rule) ? <button type="button" disabled={Boolean(pending)} onClick={() => void satisfy(rule._id)} className="rounded-lg bg-primary px-3 py-2 text-xs font-bold text-on-primary">Satisfy</button> : null}</div></article>; })}</div></section>}
      {refundEscrow ? <RefundChat escrow={escrow} onChanged={execute} /> : null}{user?.role === 'admin' && refundEscrow ? <RefundAdminPanel escrow={escrow} onChanged={execute} /> : null}
      <section className="rounded-xl bg-white p-5 sm:p-7"><h2 className="text-xl font-bold">Audit timeline</h2>{escrow.logs?.length ? <ol className="mt-6 space-y-5 border-l-2 pl-5">{escrow.logs.map((log, index) => <li key={log._id ?? `${log.createdAt}-${index}`}><div className="flex justify-between gap-2"><strong className="capitalize">{log.action.replaceAll('_', ' ')}</strong><time className="text-xs text-secondary">{formatDateTime(log.createdAt)}</time></div><p className="text-xs text-secondary">{actorName(log.actor ?? log.actorId)}</p>{log.note ? <p className="mt-2 rounded-lg bg-surface-container-low p-3 text-sm">{log.note}</p> : null}{metadataText(log.metadata) ? <p className="mt-1 break-all text-xs text-secondary">Metadata: {metadataText(log.metadata)}</p> : null}</li>)}</ol> : <p className="mt-4 text-sm text-secondary">No audit events have been recorded yet.</p>}</section>
    </div><aside className="h-fit rounded-xl bg-white p-5 xl:sticky xl:top-24"><h2 className="font-bold">Available actions</h2><div className="mt-5 space-y-3">{user?.role === 'buyer' && escrow.status === 'pending_payment' ? <button type="button" disabled={Boolean(pending)} onClick={() => void initialize()} className="w-full rounded-lg bg-primary px-4 py-3 font-bold text-on-primary">Secure payment in escrow</button> : null}{actions.requestRelease ? <button type="button" onClick={() => void action('request')} className="w-full rounded-lg bg-primary px-4 py-3 font-bold text-on-primary">Request release</button> : null}{actions.approveRelease ? <button type="button" onClick={() => void action('approve')} className="w-full rounded-lg bg-emerald-700 px-4 py-3 font-bold text-white">Approve final release</button> : null}{actions.dispute ? <button type="button" onClick={() => void action('dispute')} className="w-full rounded-lg bg-red-100 px-4 py-3 font-bold text-red-800">Raise dispute</button> : null}{actions.cancel ? <button type="button" onClick={() => void action('cancel')} className="w-full rounded-lg border border-red-300 px-4 py-3 font-bold text-red-700">Cancel escrow</button> : null}{refundEscrow ? <a href="#refund-chat" className="block rounded-lg bg-primary px-4 py-3 text-center font-bold text-on-primary">Open refund conversation</a> : null}</div></aside></div>
  </EscrowRoleLayout>;
};
export default EscrowDetails;
