import { useEffect, useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { LoaderCircle } from 'lucide-react';
import ErrorState from '../../../components/ui/ErrorState';
import LoadingState from '../../../components/ui/LoadingState';
import MediaPreview from '../../../components/property/MediaPreview';
import EscrowRoleLayout from '../../../components/escrow/EscrowRoleLayout';
import EscrowStatusBadge from '../../../components/escrow/EscrowStatusBadge';
import { ESCROW_STATUS, formatDateTime, formatEscrowMoney, requiredProgress } from '../../../components/escrow/escrowConfig';
import { useAuth } from '../../../contexts/AuthContext';
import { useAsync } from '../../../hooks/useAsync';
import { escrowService } from '../../../services/escrowService';
import type { Escrow, EscrowStatus } from '../../../types/escrow';
import { escrowBuyer, escrowProperty, escrowSeller } from '../../../types/escrow';

const refundFilters: { status: EscrowStatus; label: string }[] = [{ status: 'refund_pending', label: 'Action required' }, { status: 'refund_processing', label: 'Refund processing' }, { status: 'release_processing', label: 'Seller payout processing' }, { status: 'cancellation_pending_refund', label: 'Cancellation refund' }, { status: 'refund_failed', label: 'Failed' }, { status: 'refunded', label: 'Completed' }];
const ConditionsProgress = ({ complete, total, percent, loading }: { complete: number; total: number; percent: number; loading: boolean }) => loading ? <div className="mt-4 rounded-lg bg-surface-container-low p-3 text-xs text-secondary" role="status"><LoaderCircle className="mr-1 inline-block h-4 w-4 animate-spin align-middle" aria-hidden="true" />Loading release conditions...</div> : total > 0 ? <div className="mt-4"><div className="mb-1 flex justify-between text-xs"><span>Required conditions</span><span>{complete}/{total}</span></div><div className="h-2 overflow-hidden rounded-full bg-surface-container" role="progressbar" aria-label="Required conditions completed" aria-valuemin={0} aria-valuemax={total} aria-valuenow={complete}><div className="h-full bg-primary" style={{ width: `${percent}%` }} /></div></div> : <div className="mt-4 rounded-lg bg-surface-container-low p-3 text-xs text-secondary">No required release conditions.</div>;
const EscrowList = () => {
  const { user } = useAuth(); const { data, loading, error, execute } = useAsync(escrowService.list, true);
  const [query, setQuery] = useState(''); const [status, setStatus] = useState<'' | EscrowStatus>('');
  const [details, setDetails] = useState<Record<string, Escrow>>({});
  const requestedDetails = useRef(new Set<string>());
  useEffect(() => { const missing = (data ?? []).filter((escrow) => escrow.rules === undefined && !requestedDetails.current.has(escrow._id)); if (!missing.length) return; missing.forEach((escrow) => requestedDetails.current.add(escrow._id)); let active = true; void Promise.allSettled(missing.map((escrow) => escrowService.get(escrow._id))).then((results) => { if (!active) return; setDetails((current) => { const next = { ...current }; results.forEach((result) => { if (result.status === 'fulfilled') next[result.value._id] = result.value; }); return next; }); }); return () => { active = false; }; }, [data]);
  const escrows = useMemo(() => (data ?? []).map((escrow) => details[escrow._id] ? { ...escrow, ...details[escrow._id] } : escrow).filter((escrow) => { const property = escrowProperty(escrow); const buyer = escrowBuyer(escrow); const seller = escrowSeller(escrow); return (!status || escrow.status === status) && (!query.trim() || `${property?.title ?? ''} ${property?.location ?? ''} ${buyer?.name ?? ''} ${seller?.name ?? ''}`.toLowerCase().includes(query.trim().toLowerCase())); }), [data, details, query, status]);
  const base = user?.role === 'admin' ? '/dashboard/admin/escrows' : user?.role === 'landlord' ? '/dashboard/landlord/escrows' : '/dashboard/buyer/escrows';
  return <EscrowRoleLayout title={user?.role === 'admin' ? 'Escrow Management' : user?.role === 'landlord' ? 'Property Escrows' : 'My Escrows'} subtitle="Track secured payments, refunds, disputes, and ownership completion.">
    {user?.role === 'admin' ? <section className="mb-5 rounded-xl bg-white p-4"><h2 className="text-sm font-bold">Refund queue</h2><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => setStatus('')} className="rounded-full border px-3 py-2 text-xs font-bold">All escrows</button>{refundFilters.map((item) => <button type="button" key={item.status} onClick={() => setStatus(item.status)} className={`rounded-full px-3 py-2 text-xs font-bold ${status === item.status ? 'bg-primary text-on-primary' : 'bg-surface-container-low'}`}>{item.label} ({(data ?? []).filter((escrow) => escrow.status === item.status).length})</button>)}</div></section> : null}
    <div className="mb-6 flex flex-col gap-3 rounded-xl bg-white p-4 sm:flex-row"><label className="flex flex-1 items-center gap-2 rounded-lg bg-surface-container-low px-3"><span className="material-symbols-outlined">search</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search property or participant" className="w-full bg-transparent py-3 text-sm outline-none" /></label><select aria-label="Escrow status" value={status} onChange={(event) => setStatus(event.target.value as '' | EscrowStatus)} className="rounded-lg bg-surface-container-low px-4 py-3 text-sm"><option value="">All statuses</option>{Object.entries(ESCROW_STATUS).map(([value, item]) => <option key={value} value={value}>{item.label}</option>)}</select></div>
    {loading ? <LoadingState label="Loading escrows..." /> : error ? <ErrorState message={error} onRetry={() => void execute()} /> : escrows.length === 0 ? <div className="rounded-xl bg-white p-12 text-center"><span className="material-symbols-outlined text-5xl text-secondary/40">shield_lock</span><h2 className="mt-3 font-bold">No escrows found</h2><p className="mt-1 text-sm text-secondary">Escrows matching your filters will appear here.</p></div> : <div className="grid gap-4 xl:grid-cols-2">{escrows.map((escrow) => { const property = escrowProperty(escrow); const buyer = escrowBuyer(escrow); const progress = requiredProgress(escrow); const refund = escrow.status.startsWith('refund') || escrow.status === 'refunded' || ['cancellation_pending_refund', 'cancelled_refunded'].includes(escrow.status); return <article key={escrow._id} className="rounded-xl bg-white p-4 shadow-sm sm:p-5"><div className="flex gap-4"><div className="h-24 w-28 shrink-0 overflow-hidden rounded-lg"><MediaPreview media={property?.media?.[0]} alt={property?.title ?? 'Property'} className="h-full w-full object-cover" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-2"><div><h2 className="truncate font-bold">{property?.title ?? 'Property escrow'}</h2><p className="truncate text-xs text-secondary">{property?.location ?? 'Location unavailable'}</p></div><EscrowStatusBadge status={escrow.status} /></div><p className="mt-2 text-lg font-black text-primary">{formatEscrowMoney(escrow.amount, escrow.currency ?? property?.currency)}</p></div></div>{refund ? <div className="mt-4 grid gap-2 rounded-lg bg-surface-container-low p-3 text-xs sm:grid-cols-2"><p><strong>Buyer:</strong> {buyer?.name ?? 'Buyer'}</p><p><strong>Requested:</strong> {formatDateTime(escrow.refundRequestedAt ?? undefined)}</p><p><strong>Processing:</strong> {formatDateTime(escrow.refundProcessingAt ?? undefined)}</p><p><strong>Next:</strong> {escrow.status === 'refund_pending' ? 'Request/verify details' : escrow.status === 'refund_failed' ? 'Review and retry' : ['refund_processing', 'cancellation_pending_refund'].includes(escrow.status) ? 'Await confirmation' : 'Complete'}</p></div> : <ConditionsProgress {...progress} loading={escrow.rules === undefined} />}<div className="mt-4 flex items-center justify-between gap-3"><time className="text-xs text-secondary">Created {formatDateTime(escrow.createdAt)}</time><Link to={`${base}/${escrow._id}`} className="rounded-lg bg-primary px-4 py-2 text-xs font-bold text-on-primary">{refund ? 'Open refund' : 'View escrow'}</Link></div></article>; })}</div>}
  </EscrowRoleLayout>;
};
export default EscrowList;
