import { useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import Swal from 'sweetalert2';
import { toast } from 'sonner';
import EscrowRoleLayout from '../../../components/escrow/EscrowRoleLayout';
import EscrowStatusBadge from '../../../components/escrow/EscrowStatusBadge';
import { ESCROW_STATUS, RULE_LABELS, canSatisfyRule, escrowActions, formatDateTime, formatEscrowMoney, requiredProgress } from '../../../components/escrow/escrowConfig';
import ErrorState from '../../../components/ui/ErrorState';
import LoadingState from '../../../components/ui/LoadingState';
import MediaPreview from '../../../components/property/MediaPreview';
import { useAuth } from '../../../contexts/AuthContext';
import { useAsync } from '../../../hooks/useAsync';
import { escrowErrorDetails, escrowService } from '../../../services/escrowService';
import type { Escrow } from '../../../types/escrow';
import { escrowBuyer, escrowPayment, escrowProperty, escrowSeller, isRuleSatisfied, populated } from '../../../types/escrow';

type Action = 'request' | 'approve' | 'cancel' | 'dispute';
const notePrompt = async (title: string, required: boolean, confirmButtonText: string) => Swal.fire<string>({ title, input: 'textarea', inputLabel: required ? 'Reason (required)' : 'Audit note (optional)', inputPlaceholder: 'Add context for the audit timeline', showCancelButton: true, confirmButtonText, confirmButtonColor: '#173d32', inputValidator: (value) => required && !value.trim() ? 'A reason is required.' : undefined });
const actorName = (value: unknown) => { const actor = populated(value as { _id: string; name?: string } | string | null); return actor?.name ?? (typeof value === 'string' ? 'Participant' : 'System'); };
const metadataText = (metadata?: Record<string, unknown>) => metadata && Object.keys(metadata).length ? JSON.stringify(metadata) : null;

const EscrowDetails = () => {
  const { id = '' } = useParams(); const { user } = useAuth(); const { data: escrow, loading, error, execute } = useAsync(() => escrowService.get(id), true); const [pending, setPending] = useState<string | null>(null); const [conflict, setConflict] = useState<string | null>(null); const [ruleEligibility, setRuleEligibility] = useState<Record<string, string>>({});
  const property = escrow ? escrowProperty(escrow) : null; const buyer = escrow ? escrowBuyer(escrow) : null; const seller = escrow ? escrowSeller(escrow) : null; const payment = escrow ? escrowPayment(escrow) : null; const progress = useMemo(() => escrow ? requiredProgress(escrow) : null, [escrow]);
  const mutate = async (key: string, operation: () => Promise<Escrow>) => { if (pending) return; setPending(key); setConflict(null); try { await operation(); toast.success('Escrow updated successfully.'); await execute(); } catch (raw) { const err = escrowErrorDetails(raw); if (err.status === 409) { const missing = Array.isArray(err.missingRules) ? err.missingRules.map((item) => { if (typeof item === 'string') return item; const value = item as { description?: string; type?: keyof typeof RULE_LABELS }; return value.description ?? (value.type ? RULE_LABELS[value.type] : 'Required condition'); }).join(', ') : ''; const eligible = err.eligibleAt ? ` Eligible ${formatDateTime(err.eligibleAt)}.` : ''; if (err.eligibleAt && key.startsWith('rule-')) setRuleEligibility((current) => ({ ...current, [key.slice(5)]: err.eligibleAt! })); setConflict(`${err.message}${missing ? ` Missing: ${missing}.` : ''}${eligible}`); await execute(); } else if (err.status === 403) toast.error('You do not have permission to perform this escrow action.'); else if (err.status === 404) toast.error('This escrow is no longer available.'); else toast.error(err.message); } finally { setPending(null); } };
  const action = async (type: Action) => { if (!escrow) return; const settings = type === 'dispute' ? ['Raise a dispute', true, 'Submit dispute'] as const : type === 'cancel' ? ['Cancel this escrow?', true, 'Cancel escrow'] as const : type === 'approve' ? [escrow.status === 'disputed' ? 'Resolve dispute and release funds?' : 'Approve final release?', false, 'Approve release'] as const : ['Request release?', false, 'Request release'] as const; const result = await notePrompt(settings[0], settings[1], settings[2]); if (!result.isConfirmed) return; const note = result.value?.trim() ?? ''; if (type === 'dispute') await mutate(type, () => escrowService.dispute(escrow._id, note)); if (type === 'cancel') await mutate(type, () => escrowService.cancel(escrow._id, note)); if (type === 'request') await mutate(type, () => escrowService.requestRelease(escrow._id, note)); if (type === 'approve') await mutate(type, () => escrowService.approveRelease(escrow._id, note)); };
  const satisfy = async (ruleId: string) => { if (!escrow) return; const result = await notePrompt('Mark condition as satisfied?', false, 'Confirm condition'); if (!result.isConfirmed) return; await mutate(`rule-${ruleId}`, () => escrowService.satisfyRule(escrow._id, ruleId, result.value)); };
  const initialize = async () => { if (!escrow) return; const confirmed = await Swal.fire({ title: 'Continue to secured payment?', text: 'Paystack will process the charge. A successful payment locks funds in escrow; it does not complete the property purchase.', icon: 'question', showCancelButton: true, confirmButtonText: 'Continue to Paystack', confirmButtonColor: '#173d32' }); if (!confirmed.isConfirmed) return; setPending('payment'); try { const result = await escrowService.initializePayment(escrow._id); escrowService.redirectToPayment(result); } catch (err) { toast.error(err instanceof Error ? err.message : 'Unable to initialize escrow payment.'); setPending(null); } };

  if (loading) return <EscrowRoleLayout title="Escrow Details"><LoadingState label="Loading escrow..." /></EscrowRoleLayout>;
  if (error || !escrow || !progress) return <EscrowRoleLayout title="Escrow Details"><ErrorState message={error ?? 'Escrow not found or access was denied.'} onRetry={() => void execute()} /></EscrowRoleLayout>;
  const availableActions = escrowActions(user?.role ?? 'buyer', escrow);
  const { dispute: canDispute, requestRelease: canRequest, approveRelease: canApprove, cancel: canCancel } = availableActions;
  return <EscrowRoleLayout title="Escrow Details" subtitle={ESCROW_STATUS[escrow.status].description}>
    {conflict ? <div role="alert" className="mb-6 rounded-xl bg-amber-100 p-4 text-sm font-medium text-amber-900">{conflict}</div> : null}
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]">
      <div className="space-y-6"><section className="rounded-xl bg-white p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row"><div className="h-40 w-full overflow-hidden rounded-xl bg-surface-container-low sm:w-56"><MediaPreview media={property?.media?.[0]} alt={property?.title ?? 'Property'} className="h-full w-full object-cover" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">{property?.title ?? 'Property escrow'}</h2><p className="text-sm text-secondary">{property?.location ?? 'Location unavailable'}</p></div><EscrowStatusBadge status={escrow.status} /></div><p className="mt-5 text-3xl font-black text-primary">{formatEscrowMoney(escrow.amount, escrow.currency ?? property?.currency)}</p>{property ? <Link to={`/properties/${property._id}`} className="mt-3 inline-block text-sm font-bold text-primary hover:underline">View property details</Link> : null}</div></div><dl className="mt-6 grid gap-4 border-t border-outline-variant/20 pt-6 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs font-bold uppercase text-secondary">Buyer</dt><dd className="mt-1 font-semibold">{buyer?.name ?? '—'}</dd></div><div><dt className="text-xs font-bold uppercase text-secondary">Seller</dt><dd className="mt-1 font-semibold">{seller?.name ?? '—'}</dd></div><div><dt className="text-xs font-bold uppercase text-secondary">Created</dt><dd className="mt-1">{formatDateTime(escrow.createdAt)}</dd></div><div><dt className="text-xs font-bold uppercase text-secondary">Payment</dt><dd className="mt-1">{payment?.status ?? (escrow.status === 'pending_payment' ? 'Awaiting payment' : 'Confirmed')}</dd>{payment?.reference || escrow.paymentReference ? <dd className="mt-1 truncate text-xs text-secondary">Ref: {payment?.reference ?? escrow.paymentReference}</dd> : null}</div></dl></section>
      <section className="rounded-xl bg-white p-5 sm:p-7"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-secondary">Release progress</p><h2 className="mt-1 text-xl font-bold">Required conditions</h2></div><strong>{progress.complete}/{progress.total}</strong></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-surface-container"><div className="h-full bg-primary" style={{ width: `${progress.percent}%` }} /></div><div className="mt-6 space-y-3">{escrow.rules.map((rule) => { const satisfied = isRuleSatisfied(rule); const eligibleAt = ruleEligibility[rule._id] ?? (rule.type === 'release_after_days' && typeof rule.metadata?.eligibleAt === 'string' ? rule.metadata.eligibleAt : null); const waiting = Boolean(eligibleAt && new Date(eligibleAt).getTime() > Date.now()); return <article key={rule._id} className="rounded-xl border border-outline-variant/20 p-4"><div className="flex items-start gap-3"><span className={`material-symbols-outlined ${satisfied ? 'text-emerald-600' : 'text-secondary'}`}>{satisfied ? 'check_circle' : 'radio_button_unchecked'}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{RULE_LABELS[rule.type]}</h3><span className="rounded-full bg-surface-container-low px-2 py-0.5 text-[10px] font-bold uppercase">{rule.required ? 'Required' : 'Optional'}</span></div><p className="mt-1 text-sm text-secondary">{rule.description}</p>{satisfied ? <p className="mt-2 text-xs text-emerald-700">Satisfied by {actorName(rule.satisfiedBy)} · {formatDateTime(rule.satisfiedAt)}</p> : eligibleAt ? <p className="mt-2 text-xs text-amber-700">Eligible {formatDateTime(eligibleAt)}</p> : null}</div>{user && canSatisfyRule(user.role, escrow, rule) && !waiting ? <button type="button" disabled={Boolean(pending)} onClick={() => void satisfy(rule._id)} className="rounded-lg bg-primary px-3 py-2 text-xs font-bold text-on-primary disabled:opacity-50">{pending === `rule-${rule._id}` ? 'Saving...' : 'Satisfy'}</button> : null}</div></article>; })}</div></section>
      <section className="rounded-xl bg-white p-5 sm:p-7"><h2 className="text-xl font-bold">Audit timeline</h2>{escrow.logs.length ? <ol className="mt-6 space-y-5 border-l-2 border-surface-container pl-5">{escrow.logs.map((log, index) => <li key={log._id ?? `${log.createdAt}-${index}`} className="relative"><span className="absolute -left-[27px] top-1 h-3 w-3 rounded-full bg-primary" /><div className="flex flex-wrap items-baseline justify-between gap-2"><strong className="capitalize">{log.action.replaceAll('_', ' ')}</strong><time className="text-xs text-secondary">{formatDateTime(log.createdAt)}</time></div><p className="mt-1 text-xs text-secondary">{actorName(log.actor ?? log.actorId)}{log.fromStatus || log.toStatus ? ` · ${log.fromStatus ?? '—'} → ${log.toStatus ?? log.status ?? '—'}` : ''}</p>{log.note ? <p className="mt-2 rounded-lg bg-surface-container-low p-3 text-sm">{log.note}</p> : null}{metadataText(log.metadata) ? <p className="mt-1 break-all text-xs text-secondary">Metadata: {metadataText(log.metadata)}</p> : null}</li>)}</ol> : <p className="mt-4 text-sm text-secondary">No audit events have been recorded yet.</p>}</section></div>
      <aside className="h-fit rounded-xl bg-white p-5 xl:sticky xl:top-24"><h2 className="font-bold">Available actions</h2><p className="mt-1 text-sm text-secondary">Actions are confirmed by the server and recorded in the audit timeline.</p><div className="mt-5 space-y-3">{user?.role === 'buyer' && escrow.status === 'pending_payment' ? <button type="button" disabled={Boolean(pending)} onClick={() => void initialize()} className="w-full rounded-lg bg-primary px-4 py-3 font-bold text-on-primary disabled:opacity-50">{pending === 'payment' ? 'Starting payment...' : 'Secure payment in escrow'}</button> : null}{canRequest ? <button type="button" disabled={Boolean(pending)} onClick={() => void action('request')} className="w-full rounded-lg bg-primary px-4 py-3 font-bold text-on-primary disabled:opacity-50">Request release</button> : null}{canApprove ? <button type="button" disabled={Boolean(pending)} onClick={() => void action('approve')} className="w-full rounded-lg bg-emerald-700 px-4 py-3 font-bold text-white disabled:opacity-50">{escrow.status === 'disputed' ? 'Resolve dispute and release' : 'Approve final release'}</button> : null}{canDispute ? <button type="button" disabled={Boolean(pending)} onClick={() => void action('dispute')} className="w-full rounded-lg bg-red-100 px-4 py-3 font-bold text-red-800 disabled:opacity-50">Raise dispute</button> : null}{canCancel ? <button type="button" disabled={Boolean(pending)} onClick={() => void action('cancel')} className="w-full rounded-lg border border-red-300 px-4 py-3 font-bold text-red-700 disabled:opacity-50">Cancel escrow</button> : null}{!canRequest && !canApprove && !canDispute && !canCancel && !(user?.role === 'buyer' && escrow.status === 'pending_payment') ? <p className="rounded-lg bg-surface-container-low p-4 text-sm text-secondary">No actions are currently available for your role and this status.</p> : null}</div>{escrow.status === 'release_pending' ? <p className="mt-4 text-xs text-secondary">Completing conditions does not transfer ownership. Final administrator approval is still required.</p> : null}</aside>
    </div>
  </EscrowRoleLayout>;
};
export default EscrowDetails;
