import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { toast } from 'sonner';
import { useAuth } from '../../contexts/AuthContext';
import { ApiRequestError } from '../../lib/axios';
import type {
  DisputeResolution, ProxyEvidence, ProxyInspectionDetail, ProxyInspectionReport,
  ReportCondition, ReportRecommendation, ReportSection,
} from '../../types/proxyNetwork';
import { DECLARATION_TEXT, formatLabel, formatNgn } from '../../features/proxyNetwork/config';
import { invalidateProxyData } from '../../features/proxyNetwork/cache';
import { selectProxyActions } from '../../features/proxyNetwork/selectors';
import { proxyNetworkService, type ReportInput } from '../../services/proxyNetworkService';

const field = 'mt-2 w-full rounded-lg bg-surface-container-low px-3 py-3 text-sm';
const card = 'rounded-2xl bg-white p-5 shadow-sm';
const action = 'rounded-lg bg-primary px-4 py-3 text-sm font-bold text-on-primary disabled:opacity-50';

export const Lifecycle = ({ detail }: { detail: ProxyInspectionDetail }) => {
  const stages = ['requested', 'awaiting_price_confirmation', 'awaiting_payment', 'funded', 'scheduled', 'in_progress', 'awaiting_buyer_confirmation', 'release_pending', 'completed'];
  const current = stages.indexOf(detail.request.status);
  return <section className={card}><h2 className="font-black">Inspection lifecycle</h2><ol className="mt-4 grid gap-2 sm:grid-cols-3 lg:grid-cols-5">{stages.map((stage,index) => <li key={stage} aria-current={stage === detail.request.status ? 'step' : undefined} className={`rounded-lg border p-3 text-xs font-bold ${index <= current ? 'border-primary bg-surface-container-low' : 'border-outline-variant/20 text-secondary'}`}><span className="mr-2">{index < current ? '✓' : index + 1}.</span>{formatLabel(stage)}</li>)}</ol>{!stages.includes(detail.request.status) ? <p className="mt-3 font-bold">{formatLabel(detail.request.status)}</p> : null}<p className="mt-3 text-xs text-secondary">Service escrow: {formatLabel(detail.serviceEscrow?.status || 'not created')}</p></section>;
};

const ConversationPanel = ({ id, detail, mutate }: { id: string; detail: ProxyInspectionDetail; mutate: (fn: () => Promise<unknown>, success: string) => Promise<void> }) => {
  const [text,setText] = useState('');
  const messages = detail.conversation?.messages || [];
  return <section className={card}><h2 className="text-xl font-black">Private job conversation</h2><div className="mt-4 max-h-80 space-y-3 overflow-y-auto" aria-live="polite">{messages.length ? messages.map((message) => <div key={message._id} className={`rounded-lg p-3 text-sm ${message.kind === 'system' ? 'bg-blue-50' : message.kind === 'administrative' ? 'border border-amber-300 bg-amber-50' : 'bg-surface-container-low'}`}><p className="text-xs font-bold">{message.kind === 'administrative' ? 'RealtiQ Admin' : message.kind === 'system' ? 'System update' : typeof message.sender === 'string' || !message.sender ? 'Participant' : message.sender.name}</p><p className="mt-1 whitespace-pre-wrap break-words">{message.text}</p><time className="mt-1 block text-[11px] text-secondary">{new Date(message.createdAt).toLocaleString()}</time></div>) : <p className="text-sm text-secondary">No messages yet.</p>}</div><form className="mt-4 flex gap-2" onSubmit={(e) => { e.preventDefault(); if (!text.trim()) return; void mutate(() => proxyNetworkService.sendMessage(id,text.trim()), 'Message sent.').then(() => setText('')); }}><label className="sr-only" htmlFor="proxy-message">Message</label><textarea id="proxy-message" value={text} onChange={(e) => setText(e.target.value)} className={`${field} min-h-12 flex-1`} placeholder="Write a plain-text message" /><button disabled={!text.trim()} className={action}>Send</button></form></section>;
};

const EvidenceGallery = ({ id, evidence, canUpload, mutate }: { id: string; evidence: ProxyEvidence[]; canUpload: boolean; mutate: (fn: () => Promise<unknown>, success: string) => Promise<void> }) => {
  const [files,setFiles] = useState<File[]>([]); const [captions,setCaptions] = useState<string[]>([]); const [refreshed,setRefreshed] = useState<string[]>([]); const [error,setError] = useState('');
  const choose = (selected: File[]) => {
    const allowed = ['image/jpeg','image/png','image/webp','video/mp4','video/quicktime','application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'];
    const invalid = selected.find((file) => !allowed.includes(file.type) || file.size > 250 * 1024 * 1024);
    if (invalid) return setError(`${invalid.name} is unsupported or exceeds 250 MB.`);
    if (selected.length + evidence.length > 12) return setError('A request supports no more than 12 evidence files.');
    setError(''); setFiles(selected); setCaptions(selected.map(() => ''));
  };
  const refreshUrl = async (item: ProxyEvidence) => { if (refreshed.includes(item._id)) return; setRefreshed((old) => [...old,item._id]); await mutate(() => proxyNetworkService.getEvidence(id), 'Evidence access refreshed.'); };
  return <section className={card}><h2 className="text-xl font-black">Protected evidence</h2><p className="mt-1 text-xs text-secondary">Signed media links are short-lived and remain part of this private job; they are never added to property listing media.</p>
    <div className="mt-4 grid gap-4 sm:grid-cols-2">{evidence.map((item) => <figure key={item._id} className="overflow-hidden rounded-xl border border-outline-variant/20 p-3">{item.type === 'video' ? <video controls preload="metadata" src={item.accessUrl} onError={() => void refreshUrl(item)} className="aspect-video w-full rounded-lg bg-black" /> : item.type === 'image' ? <img src={item.accessUrl} onError={() => void refreshUrl(item)} alt={item.caption || formatLabel(item.category)} className="aspect-video w-full rounded-lg object-cover" /> : <a href={item.accessUrl} target="_blank" rel="noreferrer" className="block rounded-lg bg-surface-container-low p-5 font-bold underline">Open {formatLabel(item.category)}</a>}<figcaption className="mt-2 text-sm">{item.caption || formatLabel(item.category)}{item.fileSize ? ` · ${(item.fileSize/1024/1024).toFixed(1)} MB` : ''}</figcaption></figure>)}</div>
    {!evidence.length ? <p className="mt-4 text-sm text-secondary">No protected evidence has been uploaded.</p> : null}
    {canUpload ? <form className="mt-5 rounded-xl bg-surface-container-low p-4" onSubmit={(e) => { e.preventDefault(); if (!files.length) return; void mutate(() => proxyNetworkService.uploadEvidence(id,files,captions), 'Evidence uploaded.').then(() => { setFiles([]); setCaptions([]); }); }}><label className="block text-sm font-bold">Choose evidence files (max 12, 250 MB each)<input type="file" multiple accept=".jpg,.jpeg,.png,.webp,.mp4,.mov,.pdf,.doc,.docx" onChange={(e) => choose(Array.from(e.target.files || []))} className="mt-2 block w-full rounded-lg bg-white p-3" /></label>{files.map((file,index) => <label key={`${file.name}-${index}`} className="mt-3 block text-xs font-bold">{file.name}<input value={captions[index] || ''} onChange={(e) => setCaptions((old) => old.map((v,i) => i === index ? e.target.value : v))} placeholder="Caption" className={field} /></label>)}{error ? <p role="alert" className="mt-3 text-sm text-red-800">{error}</p> : null}<button disabled={!files.length} className={`${action} mt-4`}>Upload selected evidence</button></form> : null}
  </section>;
};

const seeded: ReportSection[] = ['Building Exterior','Roof','Walls','Floors','Doors and Windows','Electrical','Plumbing','Water Supply','Drainage','Interior Condition','Structural Observations','Road Access','Security','Neighbourhood','Visible Property Boundaries','Utilities','General Condition'].map((title) => ({ key: title.toLowerCase().replaceAll(' ','_'), title, condition: 'not_inspected' }));
const ReportPanel = ({ id, report, editable, mutate }: { id: string; report: ProxyInspectionReport | null; editable: boolean; mutate: (fn: () => Promise<unknown>, success: string) => Promise<void> }) => {
  const [draft,setDraft] = useState<ReportInput>(() => report || { sections: seeded, visibleDefects: [], positiveObservations: [], declarationAccepted: false });
  const updateSection = (index: number, patch: Partial<ReportSection>) => setDraft((old) => ({...old,sections:(old.sections || seeded).map((item,i) => i === index ? {...item,...patch} : item)}));
  const setLines = (key: 'visibleDefects'|'positiveObservations', value: string) => setDraft((old) => ({...old,[key]:value.split('\n').map((v) => v.trim()).filter(Boolean)}));
  if (!editable) return <section className={card}><h2 className="text-xl font-black">Structured condition report</h2>{!report ? <p className="mt-3 text-secondary">The Inspector has not created a report yet.</p> : <><p className="mt-2 text-sm text-secondary">Observational report; it does not replace a formal structural engineering assessment.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{report.sections.map((section) => <article key={section.key} className="rounded-lg bg-surface-container-low p-3"><h3 className="font-bold">{section.title}</h3><p className="text-sm">{formatLabel(section.condition)}</p>{section.comments ? <p className="mt-1 whitespace-pre-wrap text-sm text-secondary">{section.comments}</p> : null}</article>)}</div><dl className="mt-5 space-y-3 text-sm"><div><dt className="font-bold">Summary</dt><dd className="whitespace-pre-wrap">{report.summary || '—'}</dd></div><div><dt className="font-bold">Recommendation</dt><dd>{formatLabel(report.recommendation)}</dd></div><div><dt className="font-bold">Visible defects</dt><dd>{report.visibleDefects?.join('; ') || 'None recorded'}</dd></div><div><dt className="font-bold">Positive observations</dt><dd>{report.positiveObservations?.join('; ') || 'None recorded'}</dd></div><div><dt className="font-bold">Location confirmed</dt><dd>{report.locationConfirmed ? 'Yes' : 'No'}</dd></div><div><dt className="font-bold">Declaration</dt><dd>{report.declarationText || DECLARATION_TEXT} {report.signedByName ? `— ${report.signedByName}` : ''}</dd></div></dl></>}</section>;
  return <section className={card}><h2 className="text-xl font-black">Condition report editor</h2><p className="mt-2 text-sm text-secondary">Save a draft explicitly. This observational report does not replace a formal structural engineering assessment.</p><form className="mt-5 space-y-5" onSubmit={(e) => { e.preventDefault(); void mutate(() => proxyNetworkService.saveReport(id,draft,!!report), 'Report draft saved.'); }}>
    <label className="block text-sm font-bold">Inspection date<input type="datetime-local" value={draft.inspectionDate?.slice(0,16) || ''} onChange={(e) => setDraft((old) => ({...old,inspectionDate:e.target.value ? new Date(e.target.value).toISOString() : undefined}))} className={field} /></label>
    <div className="grid gap-4 md:grid-cols-2">{(draft.sections || seeded).map((section,index) => <fieldset key={section.key} className="rounded-xl bg-surface-container-low p-4"><legend className="font-bold">{section.title}</legend><label className="mt-2 block text-xs font-bold">Condition<select value={section.condition} onChange={(e) => updateSection(index,{condition:e.target.value as ReportCondition})} className={`${field} bg-white`}>{['excellent','good','fair','poor','not_inspected','not_applicable'].map((condition) => <option key={condition} value={condition}>{formatLabel(condition)}</option>)}</select></label><label className="mt-2 block text-xs font-bold">Comments<textarea value={section.comments || ''} onChange={(e) => updateSection(index,{comments:e.target.value})} className={`${field} min-h-20 bg-white`} /></label></fieldset>)}</div>
    <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Visible defects (one per line)<textarea value={draft.visibleDefects?.join('\n') || ''} onChange={(e) => setLines('visibleDefects',e.target.value)} className={`${field} min-h-28`} /></label><label className="text-sm font-bold">Positive observations (one per line)<textarea value={draft.positiveObservations?.join('\n') || ''} onChange={(e) => setLines('positiveObservations',e.target.value)} className={`${field} min-h-28`} /></label></div>
    {([['neighbourhoodComments','Neighbourhood comments'],['roadAccessComments','Road access comments'],['utilityComments','Utility comments'],['summary','Summary']] as const).map(([key,label]) => <label key={key} className="block text-sm font-bold">{label}<textarea value={draft[key] || ''} onChange={(e) => setDraft((old) => ({...old,[key]:e.target.value}))} className={`${field} min-h-24`} /></label>)}
    <label className="block text-sm font-bold">Recommendation<select value={draft.recommendation || ''} onChange={(e) => setDraft((old) => ({...old,recommendation:e.target.value as ReportRecommendation}))} className={field}><option value="">Select</option>{['recommended','recommended_with_concerns','further_professional_review_required','not_recommended','neutral'].map((value) => <option key={value} value={value}>{formatLabel(value)}</option>)}</select></label>
    <label className="flex gap-3 text-sm"><input type="checkbox" checked={draft.locationConfirmed || false} onChange={(e) => setDraft((old) => ({...old,locationConfirmed:e.target.checked}))} />I personally confirmed the property location.</label>
    <div className="rounded-xl border border-outline-variant/30 p-4"><p className="text-sm">{DECLARATION_TEXT}</p><label className="mt-3 flex gap-3 text-sm"><input type="checkbox" checked={draft.declarationAccepted} onChange={(e) => setDraft((old) => ({...old,declarationAccepted:e.target.checked}))} />I accept this declaration.</label><label className="mt-3 block text-sm font-bold">Sign by name<input value={draft.signedByName || ''} onChange={(e) => setDraft((old) => ({...old,signedByName:e.target.value}))} className={field} /></label></div><button className={action}>Save draft</button>
  </form></section>;
};

const AdminResolution = ({ id, detail, mutate }: { id: string; detail: ProxyInspectionDetail; mutate: (fn: () => Promise<unknown>, success: string) => Promise<void> }) => {
  const options: Array<[DisputeResolution,string,string]> = [['resume_service','Request corrections','Returns work to in progress and unlocks corrections.'],['release_inspector','Release to Inspector','Starts Paystack transfer processing; it is not final payment.'],['refund_buyer','Refund Buyer','Starts refund processing against the original payment.'],['cancel_and_refund','Cancel and refund','Starts refund processing and retains cancellation history.']];
  const [choice,setChoice] = useState<DisputeResolution>(); const [notes,setNotes] = useState('');
  return <section className={card}><h2 className="text-xl font-black">Admin dispute resolution</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{options.map(([value,label,description]) => <button key={value} type="button" onClick={() => setChoice(value)} className={`rounded-xl border p-4 text-left ${choice === value ? 'border-primary' : 'border-outline-variant/20'}`}><strong>{label}</strong><span className="mt-1 block text-xs text-secondary">{description}</span></button>)}</div><label className="mt-4 block text-sm font-bold">Required resolution notes<textarea value={notes} onChange={(e) => setNotes(e.target.value)} className={`${field} min-h-24`} /></label><button disabled={!choice || !notes.trim()} onClick={() => { if (choice && window.confirm('Confirm this dispute resolution. Provider processing actions are not terminal until webhook-confirmed.')) void mutate(() => proxyNetworkService.resolveDispute(id,choice,notes.trim()), 'Resolution submitted; refreshing authoritative state.'); }} className={`${action} mt-4`}>Confirm resolution</button><p className="mt-2 text-xs text-secondary">Current dispute: {detail.dispute?.reason}</p></section>;
};

const CompletionActions = ({ id, detail, actions, mutate }: { id: string; detail: ProxyInspectionDetail; actions: ReturnType<typeof selectProxyActions>; mutate: (fn: () => Promise<unknown>, success: string) => Promise<void> }) => {
  const [reason,setReason] = useState(''); const [description,setDescription] = useState(''); const [ack,setAck] = useState(false);
  const [rating,setRating] = useState(5); const [comment,setComment] = useState('');
  const [categories,setCategories] = useState<Record<'professionalism'|'accuracy'|'communication'|'timeliness',number | undefined>>({professionalism:undefined,accuracy:undefined,communication:undefined,timeliness:undefined});
  const checklist = [{ label:'Recorded walkthrough', ok: !detail.request.requestedServices.includes('recorded_video_walkthrough') || detail.evidence.some((item) => item.category === 'walkthrough_video') },{ label:'Inspection photos',ok:!detail.request.requestedServices.includes('photos') || detail.evidence.some((item) => item.category === 'inspection_photo')},{ label:'Report and declaration',ok:!detail.request.requestedServices.includes('condition_report') || !!detail.report?.declarationAccepted}];
  return <section className={card}><h2 className="text-xl font-black">Completion, dispute, and review</h2>{actions.submitCompletion ? <div className="mt-4"><ul className="space-y-2">{checklist.map((item) => <li key={item.label}>{item.ok ? '✓' : '○'} {item.label}</li>)}</ul><p className="mt-3 text-xs text-secondary">This checklist is guidance. The backend validates authoritative completion requirements and submission locks ordinary report editing.</p><button className={`${action} mt-4`} onClick={() => { if (window.confirm('Submit completion and lock ordinary report editing?')) void mutate(() => proxyNetworkService.submitCompletion(id),'Completion submitted for Buyer review.'); }}>Submit completion</button></div> : null}
    {actions.confirmCompletion ? <button className={`${action} mt-4`} onClick={() => { if (window.confirm('Confirm that you reviewed the evidence and report? An Admin will initiate payout; this does not complete the job yet.')) void mutate(() => proxyNetworkService.confirmCompletion(id),'Completion confirmed. Payout is awaiting Admin action.'); }}>Confirm reviewed completion</button> : null}
    {actions.dispute ? <form className="mt-5 space-y-3 rounded-xl bg-red-50 p-4" onSubmit={(e) => { e.preventDefault(); if (!reason.trim() || !ack) return; void mutate(() => proxyNetworkService.dispute(id,reason.trim(),description.trim() || undefined),'Dispute raised.').then(() => {setReason('');setDescription('');}); }}><h3 className="font-black">Raise a dispute</h3><label className="block text-sm font-bold">Reason<input required value={reason} onChange={(e) => setReason(e.target.value)} className={`${field} bg-white`} /></label><label className="block text-sm font-bold">Description<textarea value={description} onChange={(e) => setDescription(e.target.value)} className={`${field} bg-white`} /></label><label className="flex gap-3 text-sm"><input type="checkbox" checked={ack} onChange={(e) => setAck(e.target.checked)} />I understand this pauses conflicting completion/payout actions while Admin reviews the dispute.</label><button disabled={!reason.trim() || !ack} className={action}>Raise dispute</button></form> : null}
    {detail.dispute ? <div className="mt-4 rounded-xl border border-red-200 p-4"><h3 className="font-bold">Dispute: {formatLabel(detail.dispute.status)}</h3><p className="mt-2">{detail.dispute.reason}</p>{detail.dispute.description ? <p className="mt-1 text-sm text-secondary">{detail.dispute.description}</p> : null}{detail.dispute.resolution ? <p className="mt-2 text-sm">Resolution: {formatLabel(detail.dispute.resolution)} · {detail.dispute.resolutionNotes}</p> : null}</div> : null}
    {actions.review ? <form className="mt-5 space-y-3" onSubmit={(e) => { e.preventDefault(); void mutate(() => proxyNetworkService.review(id,{rating,...categories,comment:comment.trim() || undefined}),'Review submitted.'); }}><fieldset><legend className="font-bold">Overall rating</legend><div className="mt-2 flex flex-wrap gap-3">{[1,2,3,4,5].map((value) => <label key={value} className="rounded-lg bg-surface-container-low p-3"><input type="radio" name="rating" value={value} checked={rating === value} onChange={() => setRating(value)} /> {value} star{value === 1 ? '' : 's'}</label>)}</div></fieldset><div className="grid gap-3 sm:grid-cols-2">{(Object.keys(categories) as Array<keyof typeof categories>).map((key) => <label key={key} className="text-sm font-bold">{formatLabel(key)} (optional)<select value={categories[key] || ''} onChange={(e) => setCategories((old) => ({...old,[key]:e.target.value ? Number(e.target.value) : undefined}))} className={field}><option value="">Not rated</option>{[1,2,3,4,5].map((value) => <option key={value} value={value}>{value} / 5</option>)}</select></label>)}</div><label className="block text-sm font-bold">Comment<textarea value={comment} onChange={(e) => setComment(e.target.value)} className={field} /></label><button className={action}>Submit review</button></form> : null}
  </section>;
};

const ProxyWorkspace = ({ detail, requestId, role, reload, payoutVerified = false }: { detail: ProxyInspectionDetail; requestId: string; role: 'buyer'|'proxy_inspector'|'admin'; reload: () => Promise<unknown>; payoutVerified?: boolean }) => {
  const { user } = useAuth(); const [pending,setPending] = useState(false); const [missing,setMissing] = useState<string[]>([]);
  const [price,setPrice] = useState(''); const [schedule,setSchedule] = useState('');
  const actions = useMemo(() => selectProxyActions(detail,role,user?._id,payoutVerified || !!detail.payoutAccount?.verifiedAt), [detail,role,user?._id,payoutVerified]);
  const mutate = async (fn: () => Promise<unknown>, success: string) => { if (pending) return; setPending(true); setMissing([]); try { await fn(); toast.success(success); invalidateProxyData(requestId); await reload(); } catch (raw) { const err = raw instanceof Error ? raw : new Error('Action failed.'); toast.error(err.message); if (raw instanceof ApiRequestError) { const details = raw.details as { missing?: string[] } | undefined; if (details?.missing) setMissing(details.missing); if ([409,502].includes(raw.status || 0)) await reload(); } } finally { setPending(false); } };
  const property = typeof detail.request.property === 'string' ? null : detail.request.property;
  return <div className="space-y-5" aria-busy={pending}>
    <section className={card}><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-widest text-secondary">{property?.publicReference || 'Private inspection job'}</p><h1 className="mt-1 text-3xl font-black">{property?.title || 'Property inspection'}</h1><p className="mt-2 text-sm text-secondary">Request status: {formatLabel(detail.request.status)}</p></div><button onClick={() => void reload()} className="rounded-lg bg-surface-container-low px-4 py-2 text-sm font-bold">Refresh latest state</button></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><div><p className="text-xs font-bold text-secondary">Buyer</p><p>{typeof detail.request.buyer === 'string' ? 'Buyer' : detail.request.buyer.name}</p></div><div><p className="text-xs font-bold text-secondary">Independent RealtiQ Verified Property Agent</p><p>{typeof detail.request.inspector === 'string' ? 'RealtiQ Verified Property Agent' : detail.request.inspector.name}</p></div><div><p className="text-xs font-bold text-secondary">Requested services</p><p>{detail.request.requestedServices.map(formatLabel).join(', ')}</p></div></div>{detail.request.customRequirements ? <p className="mt-4 whitespace-pre-wrap rounded-lg bg-surface-container-low p-3 text-sm"><strong>Custom requirements:</strong> {detail.request.customRequirements}</p> : null}<p className="mt-4 text-xs text-secondary">The RealtiQ Verified Property Agent is an independent third party, not a RealtiQ employee. This job uses uploaded recorded media and does not include live video or calls.</p></section>
    <Lifecycle detail={detail} />
    <section className={card}><h2 className="text-xl font-black">Price negotiation</h2><p className="mt-2 text-3xl font-black">{formatNgn(detail.request.proposedPrice || detail.request.agreedPrice)}</p><div className="mt-3 flex gap-5 text-sm"><span>{detail.request.buyerPriceConfirmed ? '✓' : '○'} Buyer confirmed</span><span>{detail.request.inspectorPriceConfirmed ? '✓' : '○'} Inspector confirmed</span></div>{detail.request.priceLockedAt ? <p className="mt-2 text-sm text-emerald-800">Price locked by the backend on {new Date(detail.request.priceLockedAt).toLocaleString()}.</p> : null}{actions.proposePrice ? <form className="mt-4 flex gap-2" onSubmit={(e) => { e.preventDefault(); const amount=Number(price); if (Number.isInteger(amount) && amount > 0) void mutate(() => proxyNetworkService.proposePrice(requestId,amount),'New price proposed; both confirmations were reset.'); }}><label className="flex-1 text-sm font-bold">Whole NGN amount<input inputMode="numeric" pattern="[0-9]+" value={price} onChange={(e) => setPrice(e.target.value.replace(/\D/g,''))} className={field} /></label><button className={`${action} self-end`}>Propose</button></form> : null}{actions.confirmPrice ? <button className={`${action} mt-4`} onClick={() => { if (window.confirm(`Confirm the current price of ${formatNgn(detail.request.proposedPrice)}?`)) void mutate(() => proxyNetworkService.confirmPrice(requestId),'Price confirmation recorded.'); }}>Confirm current price</button> : null}</section>
    <section className={card}><h2 className="text-xl font-black">Payment and service escrow</h2>{detail.serviceEscrow ? <dl className="mt-4 grid gap-3 sm:grid-cols-4"><div><dt className="text-xs text-secondary">Buyer total</dt><dd className="font-bold">{formatNgn(detail.serviceEscrow.grossAmount)}</dd></div><div><dt className="text-xs text-secondary">Platform commission</dt><dd className="font-bold">{formatNgn(detail.serviceEscrow.platformFeeAmount)}</dd></div><div><dt className="text-xs text-secondary">Inspector payout</dt><dd className="font-bold">{formatNgn(detail.serviceEscrow.providerAmount)}</dd></div><div><dt className="text-xs text-secondary">Escrow status</dt><dd className="font-bold">{formatLabel(detail.serviceEscrow.status)}</dd></div></dl> : <p className="mt-3 text-secondary">Financial split will appear only after the backend creates ServiceEscrow.</p>}<p className="mt-3 text-xs text-secondary">The platform commission is deducted from Inspector payout; it is not added to the Buyer total.</p>{actions.initializePayment ? <button className={`${action} mt-4`} onClick={() => void mutate(async () => { const result=await proxyNetworkService.initializePayment(requestId); sessionStorage.setItem('realtiq.proxyPaymentContext',JSON.stringify({reference:result.reference,requestId})); if (result.redirectUrl) window.location.assign(result.redirectUrl); else toast.info(result.message || 'Resume or verify the pending payment.'); },'Payment initialized.')}>Pay securely with Paystack</button> : null}{detail.serviceEscrow && ['release_processing','refund_processing'].includes(detail.serviceEscrow.status) ? <p className="mt-4 rounded-lg bg-amber-50 p-3 font-bold">{detail.serviceEscrow.status === 'release_processing' ? 'Payout processing' : 'Refund processing'} — awaiting provider webhook confirmation.</p> : null}</section>
    {(actions.schedule || detail.request.scheduledAt) ? <section className={card}><h2 className="text-xl font-black">Schedule</h2>{detail.request.scheduledAt ? <p className="mt-2">{new Date(detail.request.scheduledAt).toLocaleString(undefined,{timeZoneName:'short'})}</p> : <p className="mt-2 text-secondary">Not scheduled.</p>}{actions.schedule ? <form className="mt-4 flex flex-wrap gap-3" onSubmit={(e) => { e.preventDefault(); const date=new Date(schedule); if (date > new Date()) void mutate(() => proxyNetworkService.schedule(requestId,date.toISOString()),'Schedule updated.'); }}><label className="text-sm font-bold">Future local date and time<input required type="datetime-local" min={new Date(Date.now()+60000).toISOString().slice(0,16)} value={schedule} onChange={(e) => setSchedule(e.target.value)} className={field} /></label><button className={`${action} self-end`}>{detail.request.scheduledAt ? 'Reschedule' : 'Schedule'}</button></form> : null}{actions.start ? <button className={`${action} mt-4`} onClick={() => { if(window.confirm('Start this funded inspection now?')) void mutate(() => proxyNetworkService.start(requestId),'Inspection started.'); }}>Start inspection</button> : null}</section> : null}
    <ConversationPanel id={requestId} detail={detail} mutate={mutate} />
    <EvidenceGallery id={requestId} evidence={detail.evidence || []} canUpload={actions.uploadEvidence} mutate={mutate} />
    <ReportPanel key={`${detail.report?._id || 'new'}-${detail.report?.signedAt || ''}`} id={requestId} report={detail.report} editable={actions.editReport} mutate={mutate} />
    {missing.length ? <div role="alert" className="rounded-xl bg-red-50 p-5 text-red-900"><h2 className="font-black">Inspection completion requirements are missing</h2><ul className="mt-2 list-disc pl-5">{missing.map((item) => <li key={item}>{item}</li>)}</ul></div> : null}
    <CompletionActions id={requestId} detail={detail} actions={actions} mutate={mutate} />
    {actions.releasePayment ? <section className={card}><h2 className="text-xl font-black">Admin payout</h2><p className="mt-2">Gross {formatNgn(detail.serviceEscrow?.grossAmount)} · commission {formatNgn(detail.serviceEscrow?.platformFeeAmount)} · Inspector payout {formatNgn(detail.serviceEscrow?.providerAmount)}</p><button className={`${action} mt-4`} onClick={() => { if(window.confirm('Initiate Inspector payout? The transfer remains processing until Paystack confirms it.')) void mutate(() => proxyNetworkService.releasePayment(requestId),'Payout processing started.'); }}>Initiate payout</button></section> : role === 'admin' && detail.request.status === 'release_pending' && !detail.payoutAccount?.verifiedAt ? <p className="rounded-xl bg-amber-50 p-4 text-sm">Payout is unavailable until the Inspector has a verified payout account.</p> : null}
    {actions.resolveDispute ? <AdminResolution id={requestId} detail={detail} mutate={mutate} /> : null}
    {role === 'proxy_inspector' && !payoutVerified ? <p className="rounded-xl bg-amber-50 p-4 text-sm">No verified payout account is configured. This does not block work unless the backend says so, but it can delay payout. <Link className="font-bold underline" to="/proxy-inspector/payout-account">Configure payout account</Link>.</p> : null}
    {role === 'admin' && detail.auditHistory?.length ? <section className={card}><h2 className="text-xl font-black">Audit history</h2><ol className="mt-4 border-l pl-5">{detail.auditHistory.map((entry) => <li key={entry._id} className="mb-4"><p className="font-bold">{formatLabel(entry.action)}</p><p className="text-sm text-secondary">{formatLabel(entry.oldStatus)} → {formatLabel(entry.newStatus)} · {new Date(entry.createdAt).toLocaleString()}</p></li>)}</ol></section> : null}
  </div>;
};
export default ProxyWorkspace;
