import { Link, useSearchParams } from 'react-router-dom';
import type { ReactNode } from 'react';
import ErrorState from '../ui/ErrorState';
import LoadingState from '../ui/LoadingState';
import { formatLabel, formatNgn } from '../../features/proxyNetwork/config';
import { useProxyResource } from '../../features/proxyNetwork/useProxyResource';
import { proxyNetworkService } from '../../services/proxyNetworkService';
import type { InspectionListFilters, ProxyInspectionStatus } from '../../types/proxyNetwork';

const ProxyJobList = ({ scope, basePath, children }: { scope: 'buyer' | 'inspector' | 'admin'; basePath: string; children?: ReactNode }) => {
  const [params, setParams] = useSearchParams();
  const filters: InspectionListFilters = { status: (params.get('status') || undefined) as ProxyInspectionStatus | undefined, from: params.get('from') || undefined, to: params.get('to') || undefined, property: params.get('property') || undefined, inspector: params.get('inspector') || undefined, buyer: params.get('buyer') || undefined, page: Number(params.get('page') || 1), limit: Number(params.get('limit') || 25) };
  const load = (signal: AbortSignal) => scope === 'inspector' ? proxyNetworkService.listInspectorTasks(filters, signal) : scope === 'admin' ? proxyNetworkService.listAdminJobs(filters, signal) : proxyNetworkService.listRequests(filters, signal);
  const resource = useProxyResource(load, [scope, params.toString()]);
  const update = (key: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(key,value); else next.delete(key); if (key !== 'page') next.set('page','1'); setParams(next); };
  return <>{children}<div className="mt-6 grid gap-3 rounded-xl bg-white p-4 sm:grid-cols-3"><label className="text-xs font-bold">Status<select value={params.get('status') || ''} onChange={(e) => update('status',e.target.value)} className="mt-2 w-full rounded-lg bg-surface-container-low p-3"><option value="">All statuses</option>{['requested','negotiating','awaiting_price_confirmation','awaiting_payment','funded','scheduled','in_progress','awaiting_buyer_confirmation','release_pending','completed','disputed','refund_pending','refunded','cancelled'].map((s) => <option key={s} value={s}>{formatLabel(s)}</option>)}</select></label><label className="text-xs font-bold">From<input type="date" value={params.get('from') || ''} onChange={(e) => update('from',e.target.value)} className="mt-2 w-full rounded-lg bg-surface-container-low p-3" /></label><label className="text-xs font-bold">To<input type="date" value={params.get('to') || ''} onChange={(e) => update('to',e.target.value)} className="mt-2 w-full rounded-lg bg-surface-container-low p-3" /></label></div>
    {resource.loading ? <LoadingState /> : null}{resource.error ? <ErrorState message={resource.error.message} onRetry={() => void resource.reload()} /> : null}
    {resource.data?.requests.length === 0 ? <p className="py-12 text-center text-secondary">No inspection jobs match these filters.</p> : null}
    <div className="mt-5 overflow-x-auto rounded-xl bg-white"><table className="w-full min-w-[800px] text-left text-sm"><thead className="border-b text-xs uppercase tracking-widest text-secondary"><tr><th className="p-4">Property</th><th className="p-4">Status</th><th className="p-4">Counterparty</th><th className="p-4">Schedule</th><th className="p-4">Agreed price</th><th className="p-4">Next action</th></tr></thead><tbody>{resource.data?.requests.map((request) => { const property = typeof request.property === 'string' ? null : request.property; const counterparty = scope === 'inspector' ? request.buyer : request.inspector; return <tr key={request._id} className="border-b border-outline-variant/10"><td className="p-4"><Link className="font-bold underline" to={`${basePath}/${request._id}`}>{property?.title || 'Property'}</Link><p className="text-xs text-secondary">{property?.publicReference || ''}</p></td><td className="p-4">{formatLabel(request.status)}</td><td className="p-4">{typeof counterparty === 'string' ? 'Participant' : counterparty.name}</td><td className="p-4">{request.scheduledAt ? new Date(request.scheduledAt).toLocaleString() : 'Not scheduled'}</td><td className="p-4 font-bold">{formatNgn(request.agreedPrice)}</td><td className="p-4">{request.status === 'awaiting_payment' && scope === 'buyer' ? 'Fund service escrow' : request.status === 'funded' && scope === 'inspector' ? 'Schedule or start' : formatLabel(request.status)}</td></tr>; })}</tbody></table></div>
    {resource.data ? <div className="mt-5 flex justify-between"><p className="text-sm text-secondary">Page {resource.data.page} · {resource.data.total} jobs</p><div className="flex gap-2"><button disabled={resource.data.page <= 1} onClick={() => update('page',String(resource.data!.page - 1))} className="rounded-lg bg-white px-4 py-2 disabled:opacity-40">Previous</button><button disabled={resource.data.page * resource.data.limit >= resource.data.total} onClick={() => update('page',String(resource.data!.page + 1))} className="rounded-lg bg-white px-4 py-2 disabled:opacity-40">Next</button></div></div> : null}</>;
};
export default ProxyJobList;
