import type { RoiEstimate, RoiEvidenceItem, RoiResults } from '../../types/roiV1';

const date = (value: string) => new Intl.DateTimeFormat(undefined, { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit', timeZoneName: 'short' }).format(new Date(value));
const number = (value: number) => new Intl.NumberFormat(undefined, { maximumFractionDigits: 4 }).format(value);
const money = (value: number, currency: string) => new Intl.NumberFormat(undefined, { style: 'currency', currency, maximumFractionDigits: 2 }).format(value);
const label = (value: string) => value.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());

const ResultGrid = ({ results, currency }: { results: RoiResults; currency: string }) => {
  const rows: Array<[string, number | undefined, 'percent' | 'money']> = [
    ['Gross rental yield', results.grossRentalYield, 'percent'], ['Vacancy allowance', results.vacancyAllowance, 'money'],
    ['Net operating income', results.netOperatingIncome, 'money'], ['Net rental yield', results.netRentalYield, 'percent'],
    ['Projected net rental income', results.projectedNetRentalIncome, 'money'], ['Projected resale proceeds', results.projectedResaleProceeds, 'money'],
    ['Selling expenses', results.sellingExpenses, 'money'], ['Projected total ROI', results.projectedTotalROI, 'percent'],
    ['Nominal annualised ROI', results.nominalAnnualisedROI, 'percent'], ['Real annualised ROI', results.realAnnualisedROI, 'percent'],
  ];
  return <dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{rows.filter(([, value]) => value !== undefined).map(([name, value, kind]) => <div key={name} className="rounded-lg bg-surface-container-low p-4"><dt className="text-sm text-secondary">{name}</dt><dd className="mt-1 text-xl font-bold">{kind === 'percent' ? `${number(value!)}%` : money(value!, currency)}{value! < 0 ? <span className="ml-2 text-xs font-medium">Negative</span> : null}</dd></div>)}</dl>;
};

const EvidenceTable = ({ title, items }: { title: string; items: RoiEvidenceItem[] }) => <section aria-labelledby={`${title}-heading`} className="space-y-3"><h3 id={`${title}-heading`} className="text-xl font-bold">{title}</h3>{items.length ? <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Metric / value</th><th className="p-3">Provenance</th><th className="p-3">Timing</th><th className="p-3">Quality</th></tr></thead><tbody>{items.map((item, index) => <tr className="border-b align-top" key={item.publicReference ?? `${item.metric}-${item.recordedAt}-${index}`}><td className="p-3"><strong>{label(item.metric)}</strong><br/>{number(item.value)} {item.currency ?? item.unit ?? ''}</td><td className="p-3">{item.provider}<br/><span className="text-secondary">Type: {item.sourceType}</span>{item.series ? <><br/>{item.series}</> : null}</td><td className="p-3">Effective: {date(item.effectiveAt)}<br/>Recorded: {date(item.recordedAt)}</td><td className="p-3">Confidence: {number(item.confidence)}<br/>Version: {item.datasetVersion}{item.fallback ? <><br/><strong>Fallback evidence</strong></> : null}{item.licence ? <><br/>Licence: {item.licence}</> : null}</td></tr>)}</tbody></table></div> : <p className="text-secondary">No items returned.</p>}</section>;

export const RoiEstimateView = ({ roi }: { roi: RoiEstimate }) => <article className="space-y-8" aria-labelledby="roi-result-heading">
  <header><p className="text-sm font-semibold">{roi.publicReference}</p><h2 id="roi-result-heading" tabIndex={-1} className="text-3xl font-bold">Evidence-backed ROI projection</h2><p className="mt-2 text-secondary">This projection uses immutable property observations, evidence available as of the selected date, and bounded assumptions. It is not an appraisal, actual return, guarantee, certification, or financial, tax, or investment advice.</p></header>
  <dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><dt>Status</dt><dd className="font-bold">{label(roi.status)}</dd></div><div><dt>Property</dt><dd>{roi.propertyReference}</dd></div><div><dt>Purpose</dt><dd>{label(roi.purpose)}</dd></div><div><dt>Period</dt><dd>{number(roi.projectionPeriodYears)} years</dd></div><div><dt>Evidence as of</dt><dd>{date(roi.asOf)}</dd></div><div><dt>Snapshot effective</dt><dd>{date(roi.propertySnapshot.effectiveAt)}</dd></div><div><dt>Snapshot recorded</dt><dd>{date(roi.propertySnapshot.recordedAt)}</dd></div><div><dt>Created</dt><dd>{date(roi.createdAt)}</dd></div></dl>
  {roi.status === 'insufficient_data' || !roi.results ? <section role="status" className="rounded-lg border p-5"><h3 className="text-xl font-bold">Not enough evidence for a reliable projection</h3><p className="text-secondary">No ROI metrics or scenarios are available for this evidence date.</p></section> : <section aria-labelledby="metrics-heading" className="space-y-4"><h3 id="metrics-heading" className="text-xl font-bold">Returned metrics</h3><ResultGrid results={roi.results} currency={roi.currency}/></section>}
  {roi.status !== 'insufficient_data' && roi.scenarios.length ? <section className="space-y-4"><h3 className="text-xl font-bold">Server-returned scenarios</h3>{roi.scenarios.map((scenario) => <div key={scenario.name} className="space-y-3 rounded-lg border p-4"><h4 className="font-bold">{scenario.name}</h4><ResultGrid results={scenario.results} currency={roi.currency}/></div>)}</section> : null}
  <EvidenceTable title="User assumptions" items={roi.assumptions}/><EvidenceTable title="Sourced evidence" items={roi.sources}/>
  <section><h3 className="text-xl font-bold">Source mix</h3><dl className="mt-2 grid gap-2 sm:grid-cols-2">{Object.entries(roi.sourceMix).map(([name, value]) => <div key={name}><dt>{name}</dt><dd>{number(value)}</dd></div>)}</dl></section>
  <section><h3 className="text-xl font-bold">Factors</h3>{roi.factors.length ? <ul className="mt-2 space-y-2">{roi.factors.map((factor) => <li key={`${factor.code}-${factor.explanation}`}><strong>{factor.code} ({factor.direction})</strong>: {factor.explanation}</li>)}</ul> : <p className="text-secondary">No factors returned.</p>}</section>
  <section className="rounded-lg border border-amber-300 bg-amber-50 p-5 text-slate-900"><h3 className="text-xl font-bold">Warnings and limitations</h3>{roi.warnings.length ? <><h4 className="mt-3 font-bold">Warnings</h4><ul className="list-disc pl-5">{roi.warnings.map((v, i) => <li key={`${i}-${v}`}>{v}</li>)}</ul></> : null}{roi.limitations.length ? <><h4 className="mt-3 font-bold">Limitations</h4><ul className="list-disc pl-5">{roi.limitations.map((v, i) => <li key={`${i}-${v}`}>{v}</li>)}</ul></> : null}</section>
  <section><h3 className="text-xl font-bold">Versions</h3><p>Algorithm: {roi.algorithmVersion} Â· Policy: {roi.policyVersion}</p><dl>{Object.entries(roi.datasetVersions).map(([name, version]) => <div key={name}><dt className="inline font-semibold">{name}: </dt><dd className="inline">{version}</dd></div>)}</dl></section>
</article>;

