export const nigeriaStateCities: Record<string, string[]> = {
  Abia: ['Aba', 'Umuahia', 'Arochukwu', 'Ohafia', 'Bende', 'Isiala Ngwa', 'Osisioma'],
  Adamawa: ['Yola', 'Mubi', 'Numan', 'Jimeta', 'Ganye', 'Michika', 'Gombi'],
  'Akwa Ibom': ['Uyo', 'Eket', 'Ikot Ekpene', 'Oron', 'Abak', 'Etinan', 'Ibeno'],
  Anambra: ['Awka', 'Onitsha', 'Nnewi', 'Ekwulobia', 'Ihiala', 'Aguleri', 'Otuocha'],
  Bauchi: ['Bauchi', 'Azare', 'Misau', 'Jamaare', 'Ningi', 'Dass', 'Toro'],
  Bayelsa: ['Yenagoa', 'Brass', 'Ogbia', 'Sagbama', 'Nembe', 'Amassoma', 'Kaiama'],
  Benue: ['Makurdi', 'Gboko', 'Otukpo', 'Katsina-Ala', 'Vandeikya', 'Adikpo', 'Ugbokolo'],
  Borno: ['Maiduguri', 'Biu', 'Bama', 'Monguno', 'Dikwa', 'Gwoza', 'Konduga'],
  'Cross River': ['Calabar', 'Ikom', 'Ogoja', 'Obudu', 'Ugep', 'Akamkpa', 'Obubra'],
  Delta: ['Asaba', 'Warri', 'Sapele', 'Ughelli', 'Agbor', 'Effurun', 'Ozoro'],
  Ebonyi: ['Abakaliki', 'Afikpo', 'Onueke', 'Ishiagu', 'Uburu', 'Ezzamgbo', 'Ikwo'],
  Edo: ['Benin City', 'Auchi', 'Ekpoma', 'Uromi', 'Irrua', 'Ubiaja', 'Okada'],
  Ekiti: ['Ado Ekiti', 'Ikere Ekiti', 'Ilawe Ekiti', 'Oye Ekiti', 'Aramoko', 'Ijero', 'Ikole'],
  Enugu: ['Enugu', 'Nsukka', 'Oji River', 'Agbani', 'Udi', 'Awgu', 'Obollo-Afor'],
  'Federal Capital Territory': ['Abuja', 'Gwarinpa', 'Maitama', 'Asokoro', 'Wuse', 'Garki', 'Kubwa', 'Lugbe', 'Kuje', 'Gwagwalada', 'Nyanya', 'Apo', 'Bwari', 'Kwali', 'Jabi', 'Kubwa', 'Lokogoma', 'Life Camp', 'Dutse Alhaji', 'Gudu', 'Wuye', 'Kado', 'Giri', 'Kubwa', 'Jabi', 'Gwarimpa'],
  Gombe: ['Gombe', 'Kaltungo', 'Billiri', 'Dukku', 'Bajoga', 'Deba', 'Nafada'],
  Imo: ['Owerri', 'Orlu', 'Okigwe', 'Mbaise', 'Oguta', 'Mbano', 'Nkwerre'],
  Jigawa: ['Dutse', 'Hadejia', 'Gumel', 'Kazaure', 'Ringim', 'Birnin Kudu', 'Babura'],
  Kaduna: ['Kaduna', 'Zaria', 'Kafanchan', 'Saminaka', 'Kagoro', 'Birnin Gwari', 'Kachia'],
  Kano: ['Kano', 'Wudil', 'Gwarzo', 'Rano', 'Bichi', 'Karaye', 'Dambatta'],
  Katsina: ['Katsina', 'Daura', 'Funtua', 'Malumfashi', 'Dutsin-Ma', 'Kankia', 'Mani'],
  Kebbi: ['Birnin Kebbi', 'Argungu', 'Yauri', 'Zuru', 'Jega', 'Kamba', 'Bagudo'],
  Kogi: ['Lokoja', 'Okene', 'Idah', 'Kabba', 'Anyigba', 'Ankpa', 'Ajaokuta'],
  Kwara: ['Ilorin', 'Offa', 'Omu-Aran', 'Jebba', 'Lafiagi', 'Pategi', 'Kaiama'],
  Lagos: ['Ikeja', 'Lagos Island', 'Victoria Island', 'Ikoyi', 'Lekki', 'Ajah', 'Epe', 'Badagry', 'Ikorodu', 'Surulere', 'Yaba', 'Maryland'],
  Nasarawa: ['Lafia', 'Keffi', 'Akwanga', 'Karu', 'Nasarawa', 'Doma', 'Wamba'],
  Niger: ['Minna', 'Bida', 'Suleja', 'Kontagora', 'Mokwa', 'Lapai', 'Agaie'],
  Ogun: ['Abeokuta', 'Ijebu Ode', 'Sagamu', 'Ota', 'Ilaro', 'Mowe', 'Ayetoro'],
  Ondo: ['Akure', 'Ondo', 'Owo', 'Ikare', 'Ore', 'Okitipupa', 'Idanre'],
  Osun: ['Osogbo', 'Ile-Ife', 'Ilesa', 'Ede', 'Iwo', 'Ikirun', 'Ejigbo'],
  Oyo: ['Ibadan', 'Ogbomoso', 'Oyo', 'Iseyin', 'Saki', 'Eruwa', 'Igbo-Ora'],
  Plateau: ['Jos', 'Bukuru', 'Pankshin', 'Shendam', 'Barkin Ladi', 'Bassa', 'Langtang'],
  Rivers: ['Port Harcourt', 'Bonny', 'Bori', 'Omoku', 'Ahoada', 'Elele', 'Oyigbo'],
  Sokoto: ['Sokoto', 'Tambuwal', 'Wurno', 'Gwadabawa', 'Illela', 'Binji', 'Goronyo'],
  Taraba: ['Jalingo', 'Wukari', 'Bali', 'Takum', 'Gembu', 'Zing', 'Lau'],
  Yobe: ['Damaturu', 'Potiskum', 'Gashua', 'Nguru', 'Geidam', 'Buni Yadi', 'Fika'],
  Zamfara: ['Gusau', 'Kaura Namoda', 'Talata Mafara', 'Anka', 'Gummi', 'Maru', 'Shinkafi'],
};

export const nigeriaStates = Object.keys(nigeriaStateCities);
