import { Link } from 'react-router-dom';
import type { StructuredPropertyFacts } from '../../types/phase45';
const label = (value?: string) => value ? value.replaceAll('_', ' ') : 'Unknown';
const StructuredFactsPanel = ({ facts, titleLink }: { facts?: StructuredPropertyFacts; titleLink?: string }) => {
  const rows: Array<[string, string]> = [
    ['Building area', facts?.areas?.buildingSquareMetres ? `${facts.areas.buildingSquareMetres.toLocaleString()} m²` : 'Unknown'], ['Land area', facts?.areas?.landSquareMetres ? `${facts.areas.landSquareMetres.toLocaleString()} m²` : 'Unknown'],
    ['Year built', facts?.yearBuilt?.toString() ?? 'Unknown'], ['Renovated', facts?.renovationYear?.toString() ?? 'Unknown'], ['Condition', label(facts?.condition)], ['Furnishing', label(facts?.furnishing)], ['Subtype', label(facts?.propertySubtype)], ['Style', facts?.architecturalStyle || 'Unknown'], ['Floors', facts?.floors?.toString() ?? 'Unknown'], ['Parking', facts?.parkingSpaces?.toString() ?? 'Unknown'], ['Road access', label(facts?.roadAccess)], ['Tenure classification', label(facts?.tenureClassification)], ['Geocode precision', label(facts?.geocodePrecision)],
  ];
  return <section className={'rounded-xl border border-outline-variant/10 bg-white p-5'} aria-labelledby={'structured-facts-title'}><h2 id={'structured-facts-title'} className={'text-xl font-black'}>Structured property facts</h2><p className={'mt-1 text-xs text-secondary'}>Unknown indicates missing evidence, not a negative property characteristic.</p><dl className={'mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3'}>{rows.map(([key, value]) => <div key={key} className={'rounded-lg bg-surface-container-low p-3'}><dt className={'text-xs font-bold text-secondary'}>{key}</dt><dd className={'mt-1 capitalize'}>{value}</dd></div>)}</dl><div className={'mt-4 rounded-lg bg-surface-container-low p-3 text-sm'}><strong>Fact verification:</strong> <span className={'capitalize'}>{label(facts?.verification?.status)}</span><span className={'text-secondary'}> · source: {label(facts?.verification?.source)}</span><p className={'mt-1 text-xs text-secondary'}>This status applies to the structured facts, not legal title validity.</p>{titleLink ? <Link className={'mt-2 inline-block font-bold text-primary underline'} to={titleLink}>Open title verification</Link> : null}</div></section>;
};
export default StructuredFactsPanel;
